"""Users table name and data type updated

Revision ID: 756515eee078
Revises: f552615eaf74
Create Date: 2021-01-08 12:40:51.201100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756515eee078'
down_revision = 'f552615eaf74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_doc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('telphone', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('rol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_verified', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('num_doc', name='user_num_doc_key')
    )
    # ### end Alembic commands ###
