"""id_medicalspecialty medicalhistory fixed

Revision ID: 8f4e40a05d56
Revises: 497b5b5b81a8
Create Date: 2021-01-11 11:45:40.828323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4e40a05d56'
down_revision = '497b5b5b81a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalHistories', sa.Column('id_medicalspecialty', sa.Integer(), nullable=True))
    op.drop_column('MedicalHistories', 'id_specialty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalHistories', sa.Column('id_specialty', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('MedicalHistories', 'id_medicalspecialty')
    # ### end Alembic commands ###
