"""Doctor Table password_changed field added

Revision ID: a0f1b8665929
Revises: 756515eee078
Create Date: 2021-01-09 07:49:44.313323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f1b8665929'
down_revision = '756515eee078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Doctors', sa.Column('password_changed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Doctors', 'password_changed')
    # ### end Alembic commands ###
